### ISSUE TITLE
Set attribute sometimes doesn't work

### ISSUE THREAD

**Issue by wilderino** [hestiaAI/json-ld-semantics#6]
model.set_attribute(
    "$.timelineObjects[].placeVisit.editActionMetadata.placeVisitSegment.location"
)
retourne False alors que "$.timelineObjects[].placeVisit.editActionMetadata.placeVisitSegment.location" fait partie des paths.

J'ai essayé plusieurs paths, certains marchent mais d'autre non. Je ne connais pas la raison

**Comment by Amustache** [comment]
Par hasard

```diff
- `"$.timelineObjects[].placeVisit.editActionMetadata.placeVisitSegment.location"`
+ `"$.timelineObjects[*].placeVisit.editActionMetadata.placeVisitSegment.location"`
```

?
